### ISSUE TITLE
invalid byte sequence in US-ASCI, have no idea with google many times.

### ISSUE THREAD

**Issue by qx** [guard/guard-jasmine#195] opened 2016-05-17 14:07 UTC
22:02:09 - ERROR - Guard::Jasmine failed to achieve its <run_on_modifications>, exception was:

> [#] ArgumentError: invalid byte sequence in US-ASCII
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-jasmine-2.0.6/lib/guard/jasmine/runner.rb:180:in `block in suite_from_first_describe'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-jasmine-2.0.6/lib/guard/jasmine/runner.rb:179:in`foreach'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-jasmine-2.0.6/lib/guard/jasmine/runner.rb:179:in `suite_from_first_describe'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-jasmine-2.0.6/lib/guard/jasmine/runner.rb:140:in`query_string_for_suite'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-jasmine-2.0.6/lib/guard/jasmine/runner.rb:118:in `jasmine_suite'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-jasmine-2.0.6/lib/guard/jasmine/runner.rb:92:in`run_jasmine_spec'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-jasmine-2.0.6/lib/guard/jasmine/runner.rb:57:in `block in run'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-jasmine-2.0.6/lib/guard/jasmine/runner.rb:55:in`each'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-jasmine-2.0.6/lib/guard/jasmine/runner.rb:55:in `each_with_object'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-jasmine-2.0.6/lib/guard/jasmine/runner.rb:55:in`run'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-jasmine-2.0.6/lib/guard/jasmine.rb:166:in `run_on_modifications'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/runner.rb:82:in`block in _supervise'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/runner.rb:79:in `catch'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/runner.rb:79:in`_supervise'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/runner.rb:61:in `block (3 levels) in run_on_changes'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/runner.rb:56:in`each'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/runner.rb:56:in `block (2 levels) in run_on_changes'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/runner.rb:119:in`block (2 levels) in _run_group_plugins'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/runner.rb:117:in `each'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/runner.rb:117:in`block in _run_group_plugins'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/runner.rb:116:in `catch'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/runner.rb:116:in`_run_group_plugins'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/runner.rb:54:in `block in run_on_changes'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/runner.rb:53:in`each'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/runner.rb:53:in `run_on_changes'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/internals/queue.rb:23:in`process'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/commander.rb:43:in `start'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/cli/environments/valid.rb:16:in`start_guard'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/cli.rb:122:in `start'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:32:in`execute'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:19:in `execute!'
> [#] /Users/ok/.rvm/gems/ruby-2.1.9/gems/guard-2.13.0/bin/_guard-core:11:in`<main>'
> 22:02:09 - INFO - Guard::Jasmine has just been fired

```
    guard (2.13.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, <= 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-jasmine (2.0.6)
      childprocess (~> 0.5)
      guard (~> 2.8)
      guard-compat (~> 1.2)
      jasmine (~> 2.2)
      multi_json (~> 1.1)
      thor (~> 0.19)
      tilt
```

**Comment by nathanstitt** [comment] 2016-05-20 00:39
Thanks for the report @qx  It looks to me like it's probably something in the spec that is outputting strings that aren't valid `US-ASCII`  However I'm not sure why Ruby's encoding is set to  US-ASCII,  is there something else in your code that's setting that encoding?  For  Ruby 2.x, you can change the encoding via: http://ruby-doc.org/core-2.2.0/Encoding.html#method-c-default_external

**Comment by qx** [comment] 2016-05-20 02:31
@nathanstitt  I don't set encoding.But after I set iterm2's Environment -> set Locale variables automatically, it works ,
<img width="953" alt="screen shot 2016-05-20 at 10 29 11" src="https://cloud.githubusercontent.com/assets/648406/15415551/e16b2e0e-1e75-11e6-8d6f-caa0ac111c44.png">

**Comment by qx** [comment] 2016-05-20 02:33
on Terminal is the same problem, It seems system problem not jasmine.
<img width="327" alt="screen shot 2016-05-20 at 10 33 05" src="https://cloud.githubusercontent.com/assets/648406/15415613/45d57994-1e76-11e6-980c-807dfdb49625.png">

**Comment by nathanstitt** [comment] 2018-06-19 15:23
Closing since it seems the issue is probably related to system encodings somewhere, sorry it took so long to circle back to this

**Closed by nathanstitt** 2018-06-19 15:23 UTC
